# Generated by Django 4.0.6 on 2022-08-04 04:31

from django.db import migrations
from apps.authentication.services import create_dev_user


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220804_0404'),
    ]

    operations = [migrations.RunPython(create_dev_user)]
